SPOOL task2
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 300

-- ORIGINAL VERSION
explain plan for 
SELECT L_ORDERKEY, L_LINENUMBER, L_QUANTITY*L_EXTENDEDPRICE
FROM LINEITEM
WHERE L_QUANTITY*L_EXTENDEDPRICE = (SELECT MAX(L.L_QUANTITY*L.L_EXTENDEDPRICE)
                                    FROM LINEITEM L )
ORDER BY L_ORDERKEY;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY); 

--IMPROVED VERSION 
EXPLAIN PLAN FOR 
SELECT L_ORDERKEY, L_LINENUMBER, MAX(L_QUANTITY*L_EXTENDEDPRICE)
FROM LINEITEM
GROUP BY L_ORDERKEY, L_LINENUMBER
ORDER BY 3 DESC;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY); 

--WORSE VERSION 
EXPLAIN PLAN FOR 
SELECT L1.L_ORDERKEY, L1.L_LINENUMBER, MAX(L1.L_QUANTITY * L1.L_EXTENDEDPRICE)
FROM LINEITEM L1, LINEITEM L2
WHERE (L1.L_QUANTITY * L1.L_EXTENDEDPRICE) > (L2.L_QUANTITY * L2.L_EXTENDEDPRICE)
GROUP BY L1.L_ORDERKEY, L1.L_LINENUMBER;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY); 

SPOOL OFF